language: python

python:
  - 3.3
  - 3.4
  - 3.5

services: postgresql

env:
  global:
# - DJANGO="x.y.z"
  - DJANGO_SETTINGS_MODULE="django_simepar_translation_server.settings"
  - PYTHONPATH="/home/gdelnegro/projects/simepar/simepar-django-translation-server"
  - PIP_USE_MIRRORS=true
# Last two for OS X, courtesy of stackoverflow.com/a/22697917/419005
# - CFLAGS=-Qunused-arguments
# - CPPFLAGS=-Qunused-arguments

install:
  - pip install -r requirements.txt
  - pip install coveralls radon
# - pip install pip-tools --quiet

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

before_script:
  python manage.py runserver &

script:
  coverage run manage.py tests
  coverage run functional_tests.py

after_success:
- pip freeze
- echo Uploading code coverage data ...; coveralls
#- echo Code complexity scores:; radon cc --min B ../pony-forum

#notifications:
#  email:
#    on_success: change
#    on_failure: always

# matrix:
#   allow_failures:
#     - python: 3.3