# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='TTP7', null=True, verbose_name='MDL7')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='TTP8', null=True, verbose_name='MDL8')),
                ('tag', models.CharField(help_text='TTP14', max_length=20, unique=True, verbose_name='MDL14')),
                ('text', models.TextField(help_text='TTP15', verbose_name='MDL15')),
                ('auxiliary_tag', models.CharField(blank=True, help_text='TTP16', max_length=20, null=True, verbose_name='MDL16')),
                ('auxiliary_text', models.TextField(blank=True, help_text='TTP17', null=True, verbose_name='MDL17')),
                ('migration_created', models.BooleanField(default=False, help_text='TTP18', verbose_name='MDL18')),
            ],
            options={
                'verbose_name': 'MTA2',
                'verbose_name_plural': 'MTP2',
            },
        ),
        migrations.CreateModel(
            name='TranslationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='TTP7', null=True, verbose_name='MDL7')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='TTP8', null=True, verbose_name='MDL8')),
                ('tag', models.CharField(help_text='TTP9', max_length=20, unique=True, verbose_name='MDL9')),
                ('name', models.TextField(help_text='TTP10', verbose_name='MDL10')),
                ('has_auxiliary_text', models.BooleanField(default=True, help_text='TTP11', verbose_name='MDL11')),
                ('auxiliary_tag', models.CharField(help_text='TTP12', max_length=20, unique=True, verbose_name='MDL12')),
            ],
            options={
                'verbose_name': 'MTA1',
                'verbose_name_plural': 'MTP1',
            },
        ),
        migrations.AddField(
            model_name='translation',
            name='type',
            field=models.ForeignKey(help_text='TTP13', on_delete=django.db.models.deletion.CASCADE, related_name='translation_translation_type', to='translation_server.TranslationType', verbose_name='MDL13'),
        ),
    ]
