# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2')),
                ('tag', models.CharField(help_text='TTP8', max_length=20, unique=True, verbose_name='MDL8')),
                ('text', models.TextField(help_text='TTP9', verbose_name='MDL9')),
                ('text_en', models.TextField(help_text='TTP9', null=True, verbose_name='MDL9')),
                ('text_pt_br', models.TextField(help_text='TTP9', null=True, verbose_name='MDL9')),
                ('auxiliary_tag', models.CharField(blank=True, help_text='TTP10', max_length=20, null=True, verbose_name='MDL10')),
                ('auxiliary_text', models.TextField(blank=True, help_text='TTP11', null=True, verbose_name='MDL11')),
                ('auxiliary_text_en', models.TextField(blank=True, help_text='TTP11', null=True, verbose_name='MDL11')),
                ('auxiliary_text_pt_br', models.TextField(blank=True, help_text='TTP11', null=True, verbose_name='MDL11')),
                ('migration_created', models.BooleanField(default=False, help_text='TTP12', verbose_name='MDL12')),
            ],
            options={
                'verbose_name_plural': 'MTP2',
                'verbose_name': 'MTA2',
            },
        ),
        migrations.CreateModel(
            name='TranslationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='TTP1', null=True, verbose_name='MDL1')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='TTP2', null=True, verbose_name='MDL2')),
                ('tag', models.CharField(help_text='TTP3', max_length=20, unique=True, verbose_name='MDL3')),
                ('name', models.TextField(help_text='TTP4', verbose_name='MDL4')),
                ('name_en', models.TextField(help_text='TTP4', null=True, verbose_name='MDL4')),
                ('name_pt_br', models.TextField(help_text='TTP4', null=True, verbose_name='MDL4')),
                ('has_auxiliary_text', models.BooleanField(default=True, help_text='TTP5', verbose_name='MDL5')),
                ('auxiliary_tag', models.CharField(help_text='TTP6', max_length=20, unique=True, verbose_name='MDL6')),
            ],
            options={
                'verbose_name_plural': 'MTP1',
                'verbose_name': 'MTA1',
            },
        ),
        migrations.AddField(
            model_name='translation',
            name='type',
            field=models.ForeignKey(help_text='TTP7', on_delete=django.db.models.deletion.CASCADE, related_name='translation_translation_type', to='translation_server.TranslationType', verbose_name='MDL7'),
        ),
    ]
