# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='auxiliary_text_en',
            field=models.TextField(blank=True, help_text='TTP17', null=True, verbose_name='MDL17'),
        ),
        migrations.AddField(
            model_name='translation',
            name='auxiliary_text_pt_br',
            field=models.TextField(blank=True, help_text='TTP17', null=True, verbose_name='MDL17'),
        ),
        migrations.AddField(
            model_name='translation',
            name='text_en',
            field=models.TextField(help_text='TTP15', null=True, verbose_name='MDL15'),
        ),
        migrations.AddField(
            model_name='translation',
            name='text_pt_br',
            field=models.TextField(help_text='TTP15', null=True, verbose_name='MDL15'),
        ),
        migrations.AddField(
            model_name='translationtype',
            name='name_en',
            field=models.TextField(help_text='TTP10', null=True, verbose_name='MDL10'),
        ),
        migrations.AddField(
            model_name='translationtype',
            name='name_pt_br',
            field=models.TextField(help_text='TTP10', null=True, verbose_name='MDL10'),
        ),
    ]
