# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 19:17
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
    translation = apps.get_model("translation_server", "TranslationType")
    translation(tag='MDL', name_pt_br="Modelo", name_en="Model", has_auxiliary_text=True,
                auxiliary_tag="TTP").save()
    translation(tag='MTA', name_pt_br="Meta", name_en="Meta", has_auxiliary_text=True, auxiliary_tag="MTP").save()
    translation(tag='GEN', name_pt_br="Texto", name_en="General Text", has_auxiliary_text=False,
                auxiliary_tag="GTP").save()
    translation(tag='ME', name_pt_br="Mensagem de erro", name_en="Error message", has_auxiliary_text=False,
                auxiliary_tag="MEE").save()


def revert_data(apps, schema_editor):
    model = apps.get_model("translation_server", "TranslationType")
    model.objects.filter(tag__in=["MDL", "MTA", "GEN", "ME"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('translation_server', '0002_auto_20161001_0302'),
    ]

    operations = [
        migrations.RunPython(load_data, revert_data)
    ]
