# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 19:21:28
from __future__ import unicode_literals

from django.db import migrations


def __load_data(**kwargs):
    apps = kwargs.pop('apps', None)
    if apps:
        translation_type = apps.get_model("translation_server", "TranslationType")
        model = apps.get_model("translation_server", "Translation")
        try:
            mdl = model.objects.get(tag=kwargs['tag'])
        except model.DoesNotExist:
            mdl = model()
        except Exception as err:
            raise err
        for k, v in kwargs.items():
            if k == "type":
                setattr(mdl, k, translation_type.objects.get(tag=v))
            else:
                setattr(mdl, k, v)
        setattr(mdl, "migration_created", True)
        mdl.save()


def clear_data(apps, schema_editor):
    model = apps.get_model("translation_server", "Translation")
    model.objects.filter(tag__in=["MDL8", "MDL9", "MDL7", "MDL10", "MDL11", "MDL12", "MTA2", "ME1"]).delete()


def load_data(apps, schema_editor):
    __load_data(apps=apps, tag="MDL8", type="MDL", text_pt_br="Tag", text_en="Tag", auxiliary_tag="TTP8", auxiliary_text_pt_br="Identificador único", auxiliary_text_en="Unique identifier")
    __load_data(apps=apps, tag="MDL9", type="MDL", text_pt_br="Texto", text_en="Text", auxiliary_tag="TTP9", auxiliary_text_pt_br="Texto da tradução", auxiliary_text_en="Translation text")
    __load_data(apps=apps, tag="MDL7", type="MDL", text_pt_br="Tipo de tradução", text_en="Translation Type", auxiliary_tag="TTP7", auxiliary_text_pt_br="Tipo de tradução do registro", auxiliary_text_en="Record translation type")
    __load_data(apps=apps, tag="MDL10", type="MDL", text_pt_br="Tag auxiliar", text_en="Auxiliary tag", auxiliary_tag="TTP10", auxiliary_text_pt_br="Identificador único do texto auxiliar", auxiliary_text_en="Auxiliary text unique identifier")
    __load_data(apps=apps, tag="MDL11", type="MDL", text_pt_br="Texto auxiliar", text_en="Auxiliary text", auxiliary_tag="TTP11", auxiliary_text_pt_br="Texto auxiliar", auxiliary_text_en="Auxiliary text")
    __load_data(apps=apps, tag="MDL12", type="MDL", text_pt_br="\"Migration\" criada", text_en="Migration created", auxiliary_tag="TTP12", auxiliary_text_pt_br="\"Migration\" criada", auxiliary_text_en="Migration created")
    __load_data(apps=apps, tag="MTA2", type="MTA", text_pt_br="Tradução", text_en="Translation", auxiliary_tag="MTP2", auxiliary_text_pt_br="Traduções", auxiliary_text_en="Translations")
    __load_data(apps=apps, tag="ME1", type="ME", text_pt_br="O texto auxiliar deve ser diferente do texto principal", text_en="The auxiliary text must be different from the primary text", auxiliary_tag="", auxiliary_text_pt_br="", auxiliary_text_en="")


class Migration(migrations.Migration):

    dependencies = [
        ('translation_server', '0003_auto_20161001_2325'),
    ]

    operations = [
        migrations.RunPython(load_data, clear_data)
    ]

        