# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 19:21:28
from __future__ import unicode_literals

from django.db import migrations


def __load_data(**kwargs):
    apps = kwargs.pop('apps', None)
    if apps:
        translation_type = apps.get_model("translation_server", "TranslationType")
        model = apps.get_model("translation_server", "Translation")
        try:
            mdl = model.objects.get(tag=kwargs['tag'])
        except model.DoesNotExist:
            mdl = model()
        except Exception as err:
            raise err
        for k, v in kwargs.items():
            if k == "type":
                setattr(mdl, k, translation_type.objects.get(tag=v))
            else:
                setattr(mdl, k, v)
        setattr(mdl, "migration_created", True)
        mdl.save()


def clear_data(apps, schema_editor):
    model = apps.get_model("translation_server", "Translation")
    model.objects.filter(tag__in=["DTSM8", "DTSM9", "DTSM7", "DTSM10", "DTSM11", "DTSM12", "DTSMT2", "DTSE1"]).delete()


def load_data(apps, schema_editor):
    __load_data(apps=apps, tag="DTSM8", type="DTSM", text_pt_br="Tag", text_en="Tag", auxiliary_tag="DTST8", auxiliary_text_pt_br="Identificador único", auxiliary_text_en="Unique identifier")
    __load_data(apps=apps, tag="DTSM9", type="DTSM", text_pt_br="Texto", text_en="Text", auxiliary_tag="DTST9", auxiliary_text_pt_br="Texto da tradução", auxiliary_text_en="Translation text")
    __load_data(apps=apps, tag="DTSM7", type="DTSM", text_pt_br="Tipo de tradução", text_en="Translation Type", auxiliary_tag="DTST7", auxiliary_text_pt_br="Tipo de tradução do registro", auxiliary_text_en="Record translation type")
    __load_data(apps=apps, tag="DTSM10", type="DTSM", text_pt_br="Tag auxiliar", text_en="Auxiliary tag", auxiliary_tag="DTST10", auxiliary_text_pt_br="Identificador único do texto auxiliar", auxiliary_text_en="Auxiliary text unique identifier")
    __load_data(apps=apps, tag="DTSM11", type="DTSM", text_pt_br="Texto auxiliar", text_en="Auxiliary text", auxiliary_tag="DTST11", auxiliary_text_pt_br="Texto auxiliar", auxiliary_text_en="Auxiliary text")
    __load_data(apps=apps, tag="DTSM12", type="DTSM", text_pt_br="\"Migration\" criada", text_en="Migration created", auxiliary_tag="DTST12", auxiliary_text_pt_br="\"Migration\" criada", auxiliary_text_en="Migration created")
    __load_data(apps=apps, tag="DTSMT2", type="DTSMT", text_pt_br="Tradução", text_en="Translation", auxiliary_tag="DTSMTP2", auxiliary_text_pt_br="Traduções", auxiliary_text_en="Translations")
    __load_data(apps=apps, tag="DTSE1", type="DTSE", text_pt_br="O texto auxiliar deve ser diferente do texto principal", text_en="The auxiliary text must be different from the primary text", auxiliary_tag="", auxiliary_text_pt_br="", auxiliary_text_en="")


class Migration(migrations.Migration):

    dependencies = [
        ('translation_server', '0003_auto_20161001_2325'),
    ]

    operations = [
        migrations.RunPython(load_data, clear_data)
    ]

        