# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation_server', '0005_auto_20161004_1950'),
    ]

    operations = [
    ]
