# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation_server', '0008_auto_20161004_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='auxiliary_text_de',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='text_de',
        ),
        migrations.RemoveField(
            model_name='translationtype',
            name='name_de',
        ),
    ]
